### ISSUE TITLE
Xbox One Controller Issues

### ISSUE THREAD

**Issue by landwalker000** [FCare/Kronos#1049]
What's the full name of the game (including region) ? Grandia English patched Japan

What's your frontend ? (standalone, libretro, ...) ? Standalone

What's your OS ? (windows, linux, OSX, ...) ? Windows 10

What's your hardware ? (CPU, GPU, ...) ? i7-9700k and RTX 3080

What's the storage type of the game (official cd, burned cd or cd image) ? Image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...) Bin/Cue

Are you using any setting different from default ? If so, precise I have the resolution increased to 4k

Did this game work previously ? Do you remember when ? Is it happening with other games ? Basically, I am trying to play the fan translation of Grandia and I can get it to work but not if I map an xbox one controller. As soon as I map a controller the emulator just boots into the system menu. If I map no inputs, the game boots. I am using a bios file as well. 

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

**Comment by LuismaSP89** [comment]
I cannot reproduce the issue, I'm using xbox one controller "wired" and it works perfectly in this game. Did you tried other games? because it seems an issue with the emulator itself when the xbox one controller is being used, since when you map something it boots the system menu.

So there's some questions here:

Are you using emulated bios or tried with it?
Did you tried other games?
Did you tried a different xbox one controller? Also with other controllers such as ds4 or xbox 360 controller?
What version of kronos are you using?
Can you please upload your kronos.ini file?

**Comment by BenjaminSiskoo** [comment]
Should be fixed with Kronos 2.2.0
