### ISSUE TITLE
[libretro] use GL/GLESv2 libs depending on available system libs

### ISSUE THREAD

**Issue by 5schatten** [FCare/Kronos#317]
I've tried to build the Kronos core (x86_64) for my LE fork but it fails since the mesa package does not build libGLESv2 but libGL. If I remove [-lGLESv2](https://github.com/FCare/Kronos/blob/extui-align/libretro/Makefile#L50) it builds fine.

On the other hand if I'm going to build it for my RPi it's missing GL.h / libGL since it relies on libGLESv2.

Can you update your Makefile and add some switches like [reicast](https://github.com/libretro/reicast-emulator/blob/master/Makefile) uses or something similiar?

**Comment by barbudreadmon** [comment]
> I'm going to build it for my RPi

Kronos relies on gles3/gl3.3, RPi is not providing any of those, it's not realistic either to run this on a quad core 1.4Ghz cpu (considering you are using RPi3B+). Don't bother with it, except if you intend to implement an alternative gles2 renderer which will makes things worse in terms of speed (so it's pointless imho).

Also, either add "libretro" in the issue subject, or use the libretro fork issue tracker.

I'll look at your ldflags issue when i have some time.

**Comment by 5schatten** [comment]
I know yabause runs pretty much way to slow on RPi but I was hoping a GL/GLES accelerated renderer would speed things up. Anyway GLES for generic systems is not that common / Kronos is the only emulator I know that would make use of it instead of standard GL.

**Comment by barbudreadmon** [comment]
> I know yabause runs pretty much way to slow on RPi

At 5-10 fps, did you really expect a fork would run 10 times faster ? Kronos is about twice faster than Yabause i think, which is already pretty great.

**Comment by 5schatten** [comment]
If I consider that yabause does not link against lGL or lGLESv2 I suspect it uses a software renderer. So speeding things up with hardware acceleration is not that uncommon. And since Mupen64plus runs not that bad on a RPi3B or S905X based system too it's obvious to have some hopes that usable Saturn emulation is achievable.
Anyway I know the architecture is hard to emulate but using GLES for generic systems is pretty new to me since it targets embedded systems.

**Comment by barbudreadmon** [comment]
> So speeding things up with hardware acceleration is not that uncommon. And since Mupen64plus runs not that bad on a RPi3B or S905X based system too it's obvious to have some hopes that usable Saturn emulation is achievable.

So because a system that is not even comparable to saturn in terms of complexity is running "not that bad on rpi3" (which means not good at all, same applies for reicast), you have "hopes" that saturn emulation is suddenly 10 times faster thanks to the VideoCore IV "beast"... So after seeing the question "will reicast OIT run well on rpi3" every week for months (which is a funny question, or not, when you realize normal reicast is already running pretty bad with really high frameskip on rpi3), it's now kronos's turn... Sorry but i find that kind of question a bit depressing... Especially since i know i'll see it every week for now with people not even checking previous answers... But i guess the fact you were the first makes it kinda ok...

Anyway, yes, kronos's rendering is targeted at GLES3 (this is a fork of YabaSanshiro, the yabause fork heavily optimized for android arm gles3 devices, except kronos is not arm centric). But it's supposedly working with any GL3.3+ device through GL compatibility mode.
