### ISSUE TITLE
No sound when a state is loaded

### ISSUE THREAD

**Issue by LuismaSP89** [FCare/Kronos#369]
When a savestate is loaded, sometimes the sound stops playing while ingame, this happens in all games I have, and I don´t know which triggers this, only I can say that this happens sometimes (2/10 times for example) and you need to restart the emulator and load the state again in order to bring the sound back.

Update: Sometimes the restart emulator method doesn´t solve the problem, maybe if you make a savestate when the sound is muted there´s no turn back, and all you can do is load the game through the normal memory save of the game and make a new savestate.

**Comment by barbudreadmon** [comment]
I think this issue has been known since old yabause, i can't tell you for sure what is involved. Afaik, the mute/unmute audio has been part of the savestate process since yabause (i'm not sure about the reason), however it is unmuted after loading/saving, so i'm not sure why sometime it's not working properly.

**Comment by BenjaminSiskoo** [comment]
It should be fixed, need to wait the next release :)
