### ISSUE TITLE
save states and cheat support in libretro version

### ISSUE THREAD

**Issue by eadmaster** [FCare/Kronos#424]
i'd like to suggest adding save states and cheat support in libretro version

**Comment by barbudreadmon** [comment]
Savestates are kinda buggy, but they are supported.
For cheat support, took me 4 years on fbalpha to implement it and that was more like an unexpected collateral damage from another feature, so honestly don't expect support anytime soon.

**Comment by zkvsky** [comment]
@barbudreadmon 
I care about one "cheat" actually, widescreen hack, can we have it available in libretro? It's available in standalone [ I was wrong it was AR cheat in standalone ]

**Comment by FCare** [comment]
What do you call widescreen? What is this option? Stretch?

**Comment by zkvsky** [comment]
@FCare Nope, it's not stretch [well, it, stretches sprites ] it extends ingame 3d FOV. Just checked standalone and can't find it, maybe it was in Sanshiro or somwhere else...

Edit. It was AR Code in cheats, widescreen ones are available freely per game
Basically this :https://www.youtube.com/watch?v=QiR_aBj-4LE

Retroarch has global cheat system, not sure if it works since kronos core crashes in UI options [ I'm using confing file to set up mine ]
It also has global shader support  [dozens to choose from ], and I'm using it for prefered crt scanlines/tv look, kronos own setting for that confused me for a second.

[ I'd rather have texture dumping/loading though.. ]

**Comment by barbudreadmon** [comment]
> since kronos core crashes in UI options [ I'm using confing file to set up mine ]

First time i hear of this, you most likely have some setup issues.

> It was AR Code in cheats, widescreen ones are available freely per game

That's an interesting cheat indeed for once. Well, i'll try to hook RA cheat system when i have some time.

>[ I'd rather have texture dumping/loading though.. ]

It would be nice, however at the moment that's far from being a priority.

**Comment by zkvsky** [comment]
@barbudreadmon 
All my cores are built from source and it only happens with kronos, it happens with binary one from RA repo too, there's nothing in logs, completly locks retroarch. I'll try clean setup later on.

Reicast [reicast retro core to be exact ] and Citra just implemented texture dumping/loading, not sure if their code can be of any help

**Comment by barbudreadmon** [comment]
I took a look and apparently the cheat system is already hooked in the kronos libretro core
