### ISSUE TITLE
Outrun text menu is messed up

### ISSUE THREAD

**Issue by FCare** [FCare/Kronos#488]
![outrun](https://user-images.githubusercontent.com/14252808/57652493-fe801e00-75cf-11e9-9509-4f7554ed1eb9.png)

**Comment by fafling** [comment]
The display is incorrect since 26/04 WIP, working correctly in 21/04 WIP . This text is displayed by NBG2 layer, some tiles are missing.

There's no difference for that layer in the VDP2 debug screen between the 2 WIP :
![Capture_outrun_VDP2](https://user-images.githubusercontent.com/7624262/57734974-78350c00-76a3-11e9-9684-223382e650dd.PNG)

Correct display in 21/04 WIP :
![Capture_outrun_20190421](https://user-images.githubusercontent.com/7624262/57735052-afa3b880-76a3-11e9-9263-5c8d6a1d84ad.PNG)

**Comment by BenjaminSiskoo** [comment]
Bug aussi avec la WIP du 16.05.2019

**Comment by BenjaminSiskoo** [comment]
Soucis sur Space Harrier.

**Comment by FCare** [comment]
A retester

**Comment by BenjaminSiskoo** [comment]
Corrigé
