### ISSUE TITLE
1.7.0 Perspective correction doesn't work

### ISSUE THREAD

**Issue by Tasosgemah** [FCare/Kronos#509]
Textures/polygons are still "wobbling" like the original.

I have set gl version to 4.5.

**Comment by FCare** [comment]
If you do not want woobling and your GPU is OpenGL 4.5, you need to use the
GPU tesselation.

Simple triangle perspective correction can not solve all the issues, but it
is accessible for all CPUs. GPU Tesselation is the best to solve the issues.

**Comment by Tasosgemah** [comment]
GPU tesselation is still wobbling on my system.

I have a GTX 1060 so it's compatible with gl 4.5. But the polys are still a bit unstable like the real Saturn.

**Comment by barbudreadmon** [comment]
With GPU tess, i confirm polygons "wobbling" in Sega Rally, textures are fine tough. It might be a regression, i think the polygons were fine a few weeks ago.

**Comment by Tasosgemah** [comment]
I can confirm Perspective Correction worked in an older version. I don't remember which one that was and i don't have such old backups but in previous 1.6.0 version also didn't work. So it's an old regression.

**Comment by fafling** [comment]
Which "wobbling" polygons are you talking about exactly ?

If that's at the beginning of the demo, it has a bad case of texture corruption with triangles perspective correction (see #481 ).

If that's about polygons at the edge of the screen, especially when the camera turns around the car at the end of the race, this is due to polygon coordinates computed by the game, and Kronos can do nothing about it. You'd have to hack the game itself to change it.

Some irregularities in polygon drawing are also due to non rectangular polygon expansion by Kronos, this is meant to prevent holes between polygons since Kronos does not use the same "anti aliased" lines drawing method as VDP1 processor.

@FCare I understand you have disabled in the last WIP this expansion in GPU and CPU tesselation  modes (commit 82422ac ). The problem is that it increases holes occurrences between polygons in Sega Rally. It's hard to take a screenshot at the exact same spot, but it is representative of the difference in CPU tesselation mode :

With expansion (21/05 WIP) :
![Capture_sega_rally_trous_20190521_2](https://user-images.githubusercontent.com/7624262/58218619-d4350b80-7d07-11e9-8e34-9d9e7f2c2c6d.PNG)

Without expansion (22/05 WIP) :
![Capture_sega_rally_trous_20190523_2](https://user-images.githubusercontent.com/7624262/58218632-e3b45480-7d07-11e9-8b47-b3925132e29d.PNG)

Maybe you could give the user the choice of enabling polygon expansion or not, so that he can choose if he wants more stable/regular polygons or less holes ?

**Comment by Tasosgemah** [comment]
"wobbling" means the textures/polys are not stable or "solid" and give the impression of wobble/wave. This is normal for the Saturn and Playstation because they lack perspective correction. Unlike the N64 which had this feature and the 3D graphics were more stable.

Older versions of Kronos (from previous year) had this option working. I tried it myself and i can confirm it. But after some updates the feature stopped working and it remains non-working in version 1.7.0.

Unfortunately, i don't seem to have an old core backup before the regression to upload.

**Comment by barbudreadmon** [comment]
I'm also positive the polygons are a lot more unstable that they were in a prior version, i'll try to find a commit where it "worked properly" and post a video.

**Comment by FCare** [comment]
It would be nice to be able to click on the VP1 image and get the correponding VDP1 drawing command. It would help to understand those holes but it is a big development work...

**Comment by BenjaminSiskoo** [comment]
Fixed
