### ISSUE TITLE
The Legend of Oasis

### ISSUE THREAD

**Issue by sickemulator** [FCare/Kronos#529]
Shadows are drawn in orange-red instead of black. (btw: The error is not present in yabasanshiro-2.5.0-c4cd45)

**Comment by fafling** [comment]
Problem is present in public v1.7.0, with emulated or real bios. It is independent of tesselation mode. It exists since the rework, v1.6.0 display was correct. Tested with US CD.

v1.7.0 display :
![Capture_oasis_shadow_1 7 0](https://user-images.githubusercontent.com/7624262/59569515-d9794200-908a-11e9-8736-957e9f6ba8ac.PNG)

Correct display in v1.6.0 :
![Capture_oasis_shadow_1 6 0](https://user-images.githubusercontent.com/7624262/59569521-f44bb680-908a-11e9-82ef-a8a2c9caa127.PNG)

VDP1 drawing command :
![Capture_oasis_shadow_VDP1](https://user-images.githubusercontent.com/7624262/59569536-35dc6180-908b-11e9-9e7e-9900079b2e5c.PNG)

The game is probably using the normal shadow, shadow processing is enabled in VDP2 debug screen :
![Capture_oasis_shadow_VDP2](https://user-images.githubusercontent.com/7624262/59569544-5d332e80-908b-11e9-9273-deb291570e57.PNG)

It seems to be a different problem from #485 because the color is different and the shadows are opaque in Legend of Oasis since rework including during the period between 7th and 12th may when normal shadows were displayed correctly in Guardian heroes.

**Comment by fafling** [comment]
Corrected on Linux by @FCare , but on Windows, shadows are still opaque in the 12th july WIP (though with a darker color than before).
![Capture_legend_of_oasis_shadows_20190712](https://user-images.githubusercontent.com/7624262/61170732-1a6f5400-a56e-11e9-8407-8d942d98da79.PNG)

**Comment by BenjaminSiskoo** [comment]
@Faffling sur la wip de mi juillet ca semble ok tu peux confirmer ?

**Comment by fafling** [comment]
Non, l'ombre est toujours opaque rouge foncé chez moi.

**Comment by fafling** [comment]
Problème dû à une particularité du matériel Nvidia, partiellement fixé par la WIP rasterizer, mais il reste des cas où l'ombre est orange. C'est peut-être quand elle est sur les tiles du NBG2 qui active la spécial priority function puisque ce sont celles qui peuvent être devant le personnage, comme la table ou les chaises dans la 1ère salle.

![Capture_legend_of_oasis_rasterizer4_shadow_orange_special_priority](https://user-images.githubusercontent.com/7624262/63573372-6e198800-c585-11e9-89a6-d55abebb1fde.PNG)

**Comment by fafling** [comment]
Ce problème résiduel est independant du hardware.

**Comment by fafling** [comment]
Fixé en OpenGL dans la WIP accurate_vdp1 du 24/09.

**Comment by fafling** [comment]
Fixé dans les 2 noyaux en WIP extui-align du 19/11.
