### ISSUE TITLE
Akumajō Dracula X: Gekka no Yasōkyoku text alignment

### ISSUE THREAD

**Issue by mishamosher** [FCare/Kronos#888]
What's the full name of the game (including region) ?
Akumajō Dracula X: Gekka no Yasōkyoku / Japan

What's your frontend ? (standalone, libretro, ...) ?
Standalone

What's your OS ? (windows, linux, OSX, ...) ?
Windows 10 64 bits

What's your hardware ? (CPU, GPU, ...) ?
i5-2450M
GeForce 525M

What's the storage type of the game (official cd, burned cd or cd image) ?
CD Image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)
cue/bin

Are you using any setting different from default ? If so, precise
Tried with emulated BIOS, version 1 and version 1.0.1 Japanese bioses. Did not touch any other setting.

Did this game work previously ? Do you remember when ? Is it happening with other games ?
Don't know. Just tried Kronos today. It works OK on SSF.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
Bug report from parent repo:
https://github.com/devmiyax/yabause/issues/206

Kronos screenshot:
- ![DX_KRONOS_2](https://user-images.githubusercontent.com/3683227/82503066-cdc1a700-9ab5-11ea-9d9a-7188d949d74c.png)

Video of the real hardware showing how it should look like:
- https://youtu.be/xX2KObZJoqU?t=189

Screenshot of SSF rendering it correctly:
- ![DX_SSF](https://user-images.githubusercontent.com/3683227/82503160-fc3f8200-9ab5-11ea-9d6d-1c9856950706.png)

**Comment by fafling** [comment]
Same problem in Yaba Sanshiro : [https://github.com/devmiyax/yabause/issues/172](https://github.com/devmiyax/yabause/issues/172)

**Comment by fafling** [comment]
Same problem than #79 .

**Comment by fafling** [comment]
Problem still present because the dialog is displayed by NBG0 and commit 9f29cce40b97ece54d9977adc04e261538f3f1a0 only addresses the issue on NBG2 and NBG3.

Save state :
[Akumajou_Dracula_X_1er_dialogue_20210520.zip](https://github.com/FCare/Kronos/files/6512043/Akumajou_Dracula_X_1er_dialogue_20210520.zip)

@FCare Unless NBG0 and NBG1pattern name timings include T0 (bottom of p. 33 of VDP2 manual), they have the same horizontal penalty as NBG2 and NBG3 if their timings don't match table 3.4 of VDP2 manual.
To check this kind of problem, it would be useful to see the value of the cycle pattern register in the VDP2 debug screen in General info panel.

**Comment by fafling** [comment]
Fixed in the last WIP by cfcde26dc0662856d607ab4fc4d41d240491bd42.
