### ISSUE TITLE
Implementing virtual overclocking

### ISSUE THREAD

**Issue by paul-met** [FCare/Kronos#969]
The possibility of virtual overclocking of processors would be very useful for 3D games, which noticeably suffer from a lack of performance.

**Comment by fafling** [comment]
Virtual overclocking can introduce issues for games that rely on processors relative speeds to complete parallel tasks. There is the risk that users will enable it for one game where it would work, and then forget it and leave it on for games incompatible with it. Nothing can be done in Kronos for such incompatibilities.
If virtual overclocking is enabled, Kronos should automatically overlay a warning for a few seconds at the start of emulation regarding potential incompatibilities that can only be solved by disabling virtual overclocking.

**Comment by FCare** [comment]
The only way to have a virtual overclocking is to speed up the screen clock. It means the emulator will sync on a rate of 50*1.5 fps or 60*15 fps for example.

That way, if you have a game running a 20 fps, we can expect to have it running at 20*1.5 fps.

But as @fafling said, this will generate issues like audio glitches. there might be also some Master SH2/Slave SH2 sync issues.

If a game has been badly coded on the original game, there is no real safe fix unless recoding the game.

As for an example, originaly, Kronos was executing the VDP1 command as fast as possible, not taking care of VDP1 original timing but this was the source of a lot of issues, due to synchronisation between VDP1 and DMA.

**Comment by paul-met** [comment]
Can't this problem be solved by evenly raising the frequency for all processors at once?

**Comment by FCare** [comment]
increasing the PAL/NTSC FPS means reducing the time spent in one emulated second. So it corresponds to increase all the frequencies used in the system.

At least, you can expect sounds to play 1.25x faster. Your games will run faster but with some side effects...

**Comment by paul-met** [comment]
The PS1 emulator implements asynchronous sound playback in case of overclocking. I think the same is possible for Saturn.

**Comment by FCare** [comment]
I do not have time right now to look on these improvement. But you can submit a pull request and I will be happy to integrate it :-)
